apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: devops-app
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
  clusterIP: None          # This makes it a Headless Service - required for StatefulSets
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: devops-app
spec:
  serviceName: postgres    # Must match the headless service above
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret     # Pulling credentials from Secret
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:                   # StatefulSet creates PVC per pod automatically
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi